name: PHPCS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

permissions:
  contents: read

jobs:
  php-cs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    - name: Runs style test
      run: composer style
